package heapmonitor;

import java.awt.Window;

/**
 *
 * @author b0yd
 */
public class OptionsJDialog extends javax.swing.JDialog {

    /**
     * Creates new form OptionsJDialog
     * @param parent
     * @param modal
     */
    public OptionsJDialog( MainFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initializeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTextbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");

        scrollTextbox.setText("Auto Scroll");
        scrollTextbox.setIconTextGap(10);
        scrollTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrollTextboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(scrollTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(scrollTextbox)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scrollTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrollTextboxActionPerformed
        
        Window parentWindow = this.getOwner();
        if( parentWindow instanceof MainFrame ){
            MainFrame theMainFrame = (MainFrame)parentWindow;
            theMainFrame.setScrollFlag( scrollTextbox.isSelected() );
        }
    }//GEN-LAST:event_scrollTextboxActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox scrollTextbox;
    // End of variables declaration//GEN-END:variables

    //========================================================================
    /**
     * 
     */
    private void initializeComponents() {
        scrollTextbox.setSelected(MainFrame.AUTOSCROLL_FLAG);
    }
}
