/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heapmonitor;

import java.awt.Font;

/**
 *
 * @author user
 */
public class TraceJPanel extends javax.swing.JPanel {

    private final MainFrame parentFrame;    
    
    /**
     * Creates new form TraceJPanel
     * @param parent
     */
    public TraceJPanel( MainFrame parent) {
        initComponents();
        initializeComponents();
        parentFrame = parent;            
    }
    
    //=======================================================================
    /**
     * 
     */
    private void initializeComponents() {
        //Set text area font
        traceJTextArea.setFont( new Font(Font.MONOSPACED, Font.PLAIN, 11 ));        
    }
    
    //======================================================================
    /**
     * 
     * @param passedTrace 
     */
    public void setStackTraceTextArea( MemoryChunk passedTrace ) {
        
        passedTrace.getTraceHistory();
        String retStr = passedTrace.getTraceHistory();
        traceJTextArea.setText( retStr );
        traceJTextArea.setCaretPosition(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        traceJPanel = new javax.swing.JScrollPane();
        traceJTextArea = new javax.swing.JTextArea();

        traceJTextArea.setColumns(20);
        traceJTextArea.setRows(5);
        traceJPanel.setViewportView(traceJTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(traceJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(traceJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane traceJPanel;
    private javax.swing.JTextArea traceJTextArea;
    // End of variables declaration//GEN-END:variables

    //=======================================================================
    /**
     * 
     */
    public void clearPanel() {        
        //Clear trace
        traceJTextArea.setText("");
    }
}
